### ISSUE TITLE
terminal not responding

### ISSUE THREAD

**Issue by cornz** [Jason3S/cSpell-Tools#1]
Hi! After installing cSpelltools even the help command doesn't do anything besides not loading. 
I'm using this on arch with the newest kernel. Any hints on how to get it working?
I'm trying to build the German dictionary from the hunspell files.

**Comment by Jason3S** [comment]
Hmm.

This is what is should show:
```sh
$ cspell-tools

  Usage: cspell-tools [options] [command]


  Commands:

    compile [options] <src...>       compile words lists into simple dictionary files.
    compile-trie [options] <src...>  Compile words lists or Hunspell dictionary into trie files used by cspell.

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

Which version of node do you have?

```sh
 node -v
```

**Comment by Jason3S** [comment]
Does this dictionary work for you? https://www.npmjs.com/package/cspell-dict-de_de

**Comment by cornz** [comment]
I'm on node 7.7.3 running on arch with 4.9.29-1 kernel.
The package you linked doesn't seem to do anything - given I installed it the right way which I'm pretty sure I did :)
